services:
  - type: web
    name: Izumi
    repo: https://github.com/Loki-Xer/jarvis.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
